export const GIF_SLICED_EVENT = 'GIF_SLICED';
export const IS_ON_CHANGE_EVENT = 'IS_ON_CHANGE';
export const ROTATE_SPEED_CHANGE_EVENT = 'ROTATE_SPEED_CHANGE';
export const EXPORT_IMG_EVENT = 'EXPORT_IMG';